[package]
name = "chap-kagi"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
html-escape = "0.2.15"
chap-plugin = { workspace = true, default-features = false, features = ["tools", "http"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
url = "2.5.8"
