[package]
name = "sage-plugin"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["provider", "tools", "http"]
provider = []
tools = []
http = ["dep:lockgate-http"]

[dependencies]
lockgate-http = { workspace = true, optional = true }
lockgate-plugin = { workspace = true }
sage-plugin-macros = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
