[package]
name = "chap-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
futures.workspace = true
lockgate.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
chap-wit.workspace = true
tempfile.workspace = true
wat = "1.255.0"
wasmprinter = "0.255.0"
wit-component.workspace = true
wit-parser.workspace = true
